# Fill in these values after creating your keystore
# Replace the placeholders with the actual values you used when generating the keystore

storePassword=codedrill
keyPassword=codedrill
keyAlias=my-key-alias
storeFile=release.keystore
